name: Release docs

on: [workflow_dispatch]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "./.github/actions/install"
      
      - name: Release Documentation
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.TAG_NAME }}
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          pnpm build && pnpm --filter @magidoc/docs release