name: Release

on: [workflow_dispatch]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: "./.github/workflows/install"

      - name: Set version
        id: version
        run: |
          echo "::set-output name=TAG_NAME::$(pnpm --silent get-version)"

      - name: Release Node Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.version.outputs.TAG_NAME }}
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          pnpm -r exec pnpm version --no-git-tag-version --allow-same-version $VERSION
          pnpm release

      - name: Release Git
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.TAG_NAME }}
          artifacts: "packages/starters/starter-*.zip"
